// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKLnfMt4ZuxmWEe4sf26gIUG21MK2wpB4',
    appId: '1:972193917705:web:ed568da4b81a6cd29201d8',
    messagingSenderId: '972193917705',
    projectId: 'app-projetos-05',
    authDomain: 'app-projetos-05.firebaseapp.com',
    databaseURL: 'https://app-projetos-05-default-rtdb.firebaseio.com',
    storageBucket: 'app-projetos-05.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5E4LvQoz__Jl2R63Z4aHUHpap3P6I0Ns',
    appId: '1:972193917705:android:1609210516fe29439201d8',
    messagingSenderId: '972193917705',
    projectId: 'app-projetos-05',
    databaseURL: 'https://app-projetos-05-default-rtdb.firebaseio.com',
    storageBucket: 'app-projetos-05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzXtnnwtNwroynVoMMo6PqMNorEwzQBJ8',
    appId: '1:972193917705:ios:63e90929f5e0951d9201d8',
    messagingSenderId: '972193917705',
    projectId: 'app-projetos-05',
    databaseURL: 'https://app-projetos-05-default-rtdb.firebaseio.com',
    storageBucket: 'app-projetos-05.appspot.com',
    iosClientId: '972193917705-pf43fvo833312bci88l9tc561ebvhtgg.apps.googleusercontent.com',
    iosBundleId: 'com.example.appProjetos',
  );
}
